version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./docker/db:/data/db